name: Jekyll _Pages Directory Demo
markdown: redcarpet
highlighter: false

pages: ./_pages
defaults:
  -
    scope:
      path: ""
    values:
      layout: page

exclude:
  - LICENSE
  - README.md
  - spec
